In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np

In [26]:
arquivos = [
    "../CsvDados/CARGA_ENERGIA_2015.csv",
    "../CsvDados/CARGA_ENERGIA_2016.csv",
    "../CsvDados/CARGA_ENERGIA_2017.csv",
    "../CsvDados/CARGA_ENERGIA_2018.csv",
    "../CsvDados/CARGA_ENERGIA_2019.csv",
    "../CsvDados/CARGA_ENERGIA_2020.csv",
    "../CsvDados/CARGA_ENERGIA_2021.csv",
    "../CsvDados/CARGA_ENERGIA_2022.csv",
    "../CsvDados/CARGA_ENERGIA_2023.csv",
    "../CsvDados/CARGA_ENERGIA_2024.csv",
    "../CsvDados/CARGA_ENERGIA_2025.csv",
]

df = pd.concat(
    [pd.read_csv(arq, sep=';', encoding='utf-8') for arq in arquivos],
    ignore_index=True
)

print(f'✅ {df.shape[0]:,} linhas carregadas')

✅ 16,072 linhas carregadas

In [23]:
df.head()

  id_subsistema        nom_subsistema din_instante  val_cargaenergiamwmed
0             N                 Norte   2015-01-01            4541.005167
1            NE              Nordeste   2015-01-01            8308.521949
2             S                   Sul   2015-01-01            7717.620040
3            SE  Sudeste/Centro-Oeste   2015-01-01           30874.778708
4             N                 Norte   2015-01-02            4886.834250

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16072 entries, 0 to 16071
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_subsistema          16072 non-null  str
 1   nom_subsistema         16072 non-null  str
 2   din_instante           16072 non-null  str
 3   val_cargaenergiamwmed  16068 non-null  float64
dtypes: float64(1), str(3)
memory usage: 502.4 KB

In [25]:
df.describe()

       val_cargaenergiamwmed
count           16068.000000
mean            16964.393600
std             13103.657723
min              3969.773875
25%              8408.050559
50%             11260.678479
75%             21024.181104
max             55584.896708